# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-15 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publication_scheduler', '0003_auto_20170415_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publication_scheduler.Category'),
        ),
    ]
